language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0

before_script:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./travis-tests.sh
script:
  - ./travis-build.sh
  - ./travis-tests.sh