version: '{build}'
skip_tags: true
image: Visual Studio 2017
branches:
  only:
    - master
    - deploy
environment:
  # this is how to set encrypted variable. Go to "Settings" -> "Encrypt YAML" page in account menu to encrypt data.
  nuget_api_key:
    secure: bQrrcrk3oT7hObubXjbx6Qkw76tsKeDzC6r7cLhc9pEzy8T75uQDQIJhu800BDaw

build_script:
  - dotnet restore
  - dotnet build
  # builds get stuck?!
  #- dotnet test src/Mongo2GoTests 

for:
-
  branches:
    only:
    - "deploy"

  deploy_script:
    - call package_create.cmd
    - call package_push.cmd %nuget_api_key%
