<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Espresso3389.HttpStream" Version="2.0.68" />
    <PackageReference Include="NuGet.Versioning" Version="6.13.2" />
  </ItemGroup>
  
</Project>
